import Button from "@/components/Button";
import CardEvent from "@/components/cards/CardEvent";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import Head from "next/head";
import Pagination from "@/components/Pagination";
import { useRecoilState } from "recoil";
import navigateState from "@/recoil/atoms/navigateAtom";
import { useEffect } from "react";

function Event() {
  const [navigation, setNavigation] = useRecoilState(navigateState);

  useEffect(() => {
    setNavigation("event");
  }, [navigation]);

  return (
    <>
      <Head>
        <title>solotechnopark.go.id</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          href="https://solotechnopark.id/wp-content/uploads/2021/09/Solo-Tecno.png"
        />
      </Head>
      <main>
        <Navbar />

        <section>
          <div className="container">
            <div
              className={
                "px-10 py-10 grid grid-cols-1 lg:grid-cols-4 gap-10 bg-red-50 rounded-lg"
              }
            >
              <div>
                <label className="font-bold">Tanggal Mulai</label>
                <input
                  className="block border py-3 px-10 w-full rounded-full mt-5"
                  type="date"
                />
              </div>
              <div>
                <label className="font-bold">Tanggal Akhir</label>
                <input
                  className="block border py-3 px-10 w-full rounded-full mt-5"
                  type="date"
                />
              </div>
              <div>
                <label className="font-bold">Kategori</label>
                <select className="block border py-4 px-10 w-full rounded-full mt-5">
                  <option>---Pilih Kategori----</option>
                  <option>---Pilih Kategori----</option>
                  <option>---Pilih Kategori----</option>
                </select>
              </div>
              <div className="flex items-end">
                <Button
                  className={
                    "bg-primary-100 text-white w-full hover:opacity-50"
                  }
                >
                  Cari Event
                </Button>
              </div>
            </div>
          </div>
        </section>

        <section>
          <div className="container my-20">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-10">
              <CardEvent />
              <CardEvent />
              <CardEvent />
              <CardEvent />
              <CardEvent />
              <CardEvent />
              <CardEvent />
              <CardEvent />
              <CardEvent />
            </div>
            <div className="flex justify-center">
              <Pagination />
            </div>
          </div>
        </section>
      </main>
      <Footer />
    </>
  );
}

export default Event;
