import Button from "@/components/Button";
import Card from "@/components/Card";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import Head from "next/head";
import React from "react";

function index() {
  return (
    <>
      <Head>
        <title>solotechnopark.go.id</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          href="https://solotechnopark.id/wp-content/uploads/2021/09/Solo-Tecno.png"
        />
      </Head>
      <main>
        <Navbar />

        <section>
          <div className="container pb-20">
            <Card
              className={
                "border px-10 py-10 grid grid-cols-1 lg:grid-cols-4 gap-10"
              }
            >
              <div>
                <label className="font-bold">Tanggal Mulai</label>
                <input
                  className="block border py-3 px-10 w-full rounded-full mt-5"
                  type="date"
                />
              </div>
              <div>
                <label className="font-bold">Tanggal Akhir</label>
                <input
                  className="block border py-3 px-10 w-full rounded-full mt-5"
                  type="date"
                />
              </div>
              <div>
                <label className="font-bold">Kategori</label>
                <select className="block border py-4 px-10 w-full rounded-full mt-5">
                  <option>---Pilih Kategori----</option>
                  <option>---Pilih Kategori----</option>
                  <option>---Pilih Kategori----</option>
                </select>
              </div>
              <div className="flex items-end">
                <Button
                  className={
                    "bg-primary-100 text-white w-full hover:opacity-50"
                  }
                >
                  Cari Event
                </Button>
              </div>
            </Card>
          </div>
        </section>
      </main>
      <Footer />
    </>
  );
}

export default index;
