import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import Head from "next/head";
import React from "react";

function Berita() {
  return (
    <>
      <Head>
        <title>solotechnopark.go.id</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          href="https://solotechnopark.id/wp-content/uploads/2021/09/Solo-Tecno.png"
        />
      </Head>
      <main>
        <Navbar />
        <section className="bg-memphis">
          <div className="container py-20">
            <h1>Hai sayang</h1>
          </div>
        </section>
      </main>
      <Footer />
    </>
  );
}

export default Berita;
