// import styles from "@/styles/Home.module.css";
import Head from "next/head";
import Navbar from "@/components/Navbar";
import Button from "@/components/Button";
import ThumbProfile from "@/components/ThumbProfile";
import Card from "@/components/cards/Card";
import CardSektor from "@/components/cards/CardSektor";
import IconManufaktur from "@/images/icon-manufactur.svg";
import KawasanSTP from "@/images/Kawsan-STP-6.png";
import FungsiDanPeran from "@/images/Fungsi-dan-Peran.png";
import Image from "next/image";
import Mitra from "@/components/Mitra";
import CardLayanan from "@/components/cards/CardLayanan";
import Testimonial from "@/components/Testimonial";
import Event from "@/components/Event";
import Footer from "@/components/Footer";
import navigateState from "@/recoil/navigateAtom";
import { useRecoilState, useRecoilValue } from "recoil";
import { useEffect } from "react";

const dataLayanan = [
  {
    foto: "https://solotechnopark.id/wp-content/uploads/2022/12/Layanan-Inkubasi.png",
    layanan: "Layanan Inkubasi",
    deskripsi:
      "Pra Inkubasi Bisnis dan Teknologi, Inkubasi Bisnis dan Teknologi, Hilirisasi Riset Perguruan Tinggi, Coworking Space.",
  },
  {
    foto: "https://solotechnopark.id/wp-content/uploads/2022/12/Layanan-Teknis.png",
    layanan: "Layanan Teknis",
    deskripsi:
      "Diklat Mekanik Manufaktur, Diklat Desain Manufaktur, Diklat General Welding, Diklat Underwater Wet Welding, Diklat Otomasi, Diklat Mekanik Garmen, Diklat Basic Aircraft Structure.",
  },
  {
    foto: "https://solotechnopark.id/wp-content/uploads/2022/12/Pendukunga.png",
    layanan: "Layanan Pendukung",
    deskripsi:
      "Diklat Mekanik Manufaktur, Diklat Desain Manufaktur, Diklat General Welding, Diklat Underwater Wet Welding, Diklat Otomasi, Diklat Mekanik Garmen, Diklat Basic Aircraft Structure",
  },
  {
    foto: "https://solotechnopark.id/wp-content/uploads/2022/12/Pengembangan-Teknoologi.png",
    layanan: "Pengembangan Teknologi",
    deskripsi:
      "Layanan Konsultasi Mitra Industri, Layanan Produksi, Spare Part Industri, Precision Part, Mold Maker, Fabrikasi, Prototype untuk UMKM/IKM.",
  },
];

const dataCluster = [
  {
    id_cluster: 416252,
    foto: "http://www.w3.org/2000/svg",
    nama_cluster: "Cluster Manufaktur",
    divisi:
      '["Mekanik dan Desain","Manufaktur","Pengelasan (General & Under Water)","Otomasi","Oil and Gas Training"]',
  },
  {
    id_cluster: 553975,
    foto: "http://www.w3.org/2000/svg",
    nama_cluster: "Cluster Technopreneurship",
    divisi:
      '["Mekanik dan Desain","Manufaktur","Pengelasan (General & Under Water)","Otomasi","Oil and Gas Training"]',
  },
  {
    id_cluster: 645611,
    foto: "http://www.w3.org/2000/svg",
    nama_cluster: "Cluster Industri Kreatif",
    divisi:
      '["Mekanik dan Desain","Manufaktur","Pengelasan (General & Under Water)","Otomasi","Oil and Gas Training"]',
  },
];

export default function Home() {
  const [navigation, setNavigation] = useRecoilState(navigateState);

  useEffect(() => {
    setNavigation("beranda");
  }, [navigation]);

  return (
    <>
      <Head>
        <title>solotechnopark.go.id</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          href="https://solotechnopark.id/wp-content/uploads/2021/09/Solo-Tecno.png"
        />
      </Head>
      <main>
        <header className="bg-header-1 bg-set">
          <Navbar />
          <div className="container lg:h-[88vh] pb-20 grid lg:grid-cols-2 md:gap-20">
            <div className="flex flex-col items-start justify-center py-5 lg:py-5">
              <h1 className="head-1">
                Kawasan <strong className="text-primary-100">Inovatif</strong>{" "}
                dan Berdaya Saing International
              </h1>
              <p className="paragraph">
                Pusat Inovasi dan Vokasi yang Memadukan Unsur Pengembangan
                Iptek, Kebutuhan Pasar, Industri dan Bisnis Untuk Penguatan Daya
                Saing Daerah.
              </p>
              <Button className="bg-primary-100 text-white hover:opacity-50">
                Layanan Kami
              </Button>
            </div>
            <div className="md:flex items-center justify-end py-5 lg:py-0">
              <ThumbProfile />
            </div>
          </div>
        </header>

        <section className="bg-primary-100 bg-header-2 bg-no-repeat bg-cover bg-center">
          <div className="container text-center py-20 lg:py-20">
            <h2 className="head-3 uppercase text-center mx-auto">
              3 Cluster 9 Sektor
            </h2>

            <div className="lg:grid lg:grid-cols-3 gap-10 my-20">
              {dataCluster &&
                dataCluster.map((data) => {
                  return (
                    <Card key={data.id_cluster} className="p-5">
                      <CardSektor
                        src={data.foto}
                        title={data.nama_cluster}
                        desc={JSON.parse(data.divisi)}
                      />
                    </Card>
                  );
                })}

              {console.log(dataCluster)}
            </div>
          </div>
        </section>

        <section className=" bg-no-repeat bg-cover bg-center bg-body-1">
          <div className="container py-20 flex flex-col justify-end items-center">
            <Image className="pt-10" src={KawasanSTP} alt="kawasan STP" />

            <span className="lg:absolute right-96 z-0">
              <h2 className="head-3 font-normal text-primary-100 italic text-center lg:max-w-sm">
                Where <strong>Competence Innovation, Technology,</strong> and{" "}
                <strong>Bussines Grow</strong>
              </h2>
            </span>
          </div>
        </section>

        <section className="bg-no-repeat">
          <div className="container py-20">
            <h2 className="capitalize head-3 mx-auto text-center">
              Mitra kami dalam berkolaborasi dan bertumbuh bersama
            </h2>
            <div className="flex flex-wrap justify-center text-center py-5 lg:py-10 lg:px-10 mt-20 gap-5  rounded-md">
              <Mitra />
              <Mitra />
              <Mitra />
              <Mitra />
              <Mitra />
              <Mitra />
              <Mitra />
              <Mitra />
              <Mitra />
              <Mitra />
              <Mitra />
              <Mitra />
              <Mitra />
              <Mitra />
              <Mitra />
              <Mitra />
              <Mitra />
              <Mitra />
              <Mitra />
            </div>
          </div>
        </section>

        <section className="bg-body-4 bg-no-repeat bg-top bg-cover">
          <div className="container py-20">
            <h2 className="capitalize head-3 mx-auto text-center text-white">
              Layanan dasar solo technopark
            </h2>
            <div className="flex flex-wrap justify-center mt-10 gap-10">
              {dataLayanan &&
                dataLayanan.map((data, i) => {
                  return (
                    <CardLayanan
                      key={i}
                      src={data.foto}
                      title={data.layanan}
                      desc={data.deskripsi}
                    />
                  );
                })}
            </div>
          </div>
        </section>

        <section className="bg-body-5 bg-no-repeat bg-cover">
          <div className="container py-20">
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-10">
              <Image className="w-full" src={FungsiDanPeran} alt="flow" />
              <div className="mx-auto flex flex-col justify-center items-start">
                <h4 className="uppercase text-lg font-medium text-gray-600">
                  fungsi dan peran
                </h4>
                <h2 className="capitalize head-2 my-5">
                  <strong className="text-primary-100">Sinergi </strong> Antara
                  Akademisi, Bisnis, Goverment, Community, dan Media
                </h2>
                <p className="paragraph">
                  Menjadi kawasan terpadu dunia industri, perguruan tinggi,
                  riset dan teknologi serta kewirausahaan berbasis teknologi dan
                  inovasi bagi industri kecil menengah dalam rangka peningkatan
                  daya saing dan pertumbuhan ekonomi daerah. Peran media
                  mensupport semua aktivitas di Solo Technopark tersebut.
                </p>
              </div>
            </div>
          </div>
        </section>

        <section className="bg-primary-100 bg-body-6 bg-no-repeat bg-cover py-40">
          <div className="container md:py-20">
            <div className="max-w-4xl mx-auto py-10 px-5 md:p-20 text-center bg-dark-transparent-100 backdrop-blur-sm rounded-xl text-white">
              <h2 className="head-2 text-center mx-auto lg:max-w-2xl">
                Where Competence, Innovation, Technology and Business Grow
              </h2>
              <p className="text-xl py-5">
                Daftar ke diklat yang kami sediakan.
              </p>
              <Button className={"bg-primary-100 text-white hover:opacity-50"}>
                Daftar
              </Button>
            </div>
          </div>
        </section>

        <section className="bg-body-7 bg-no-repeat bg-right-bottom">
          <div className="container py-20">
            <h2 className="capitalize head-3 mx-auto text-center">
              Kesan Untuk Solo Technopark
            </h2>
            <div className="max-w-4xl mx-auto mt-20 -z-10">
              <Testimonial />
            </div>
          </div>
        </section>

        <section className="bg-body-8 bg-no-repeat bg-center bg-cover">
          <div className="container pt-20 pb-10">
            <div className="flex items-center justify-between lg:px-16">
              <div>
                <h3 className="capitalize head-4">wawasan</h3>
                <h2 className="capitalize head-3">event terbaru</h2>
              </div>
              <Button className="bg-primary-100 text-white hover:opacity-50">
                Event Lainnya
              </Button>
            </div>
            <div className="flex flex-wrap  justify-evenly items-center">
              <Event />
              <Event />
              <Event />
            </div>
          </div>
          <div className="container pt-10 pb-20">
            <div className="flex flex-wrap items-center justify-between lg:px-16">
              <div>
                <h3 className="capitalize head-4">wawasan</h3>
                <h2 className="capitalize head-3">berita terbaru</h2>
              </div>
              <Button className="bg-primary-100 text-white hover:opacity-50">
                Berita Lainnya
              </Button>
            </div>
            <div className="flex flex-wrap justify-evenly items-center">
              <Event />
              <Event />
              <Event />
            </div>
          </div>
        </section>
      </main>
      <Footer />
    </>
  );
}
