import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import Head from "next/head";
import React from "react";
import HeroImage from "@/images/Foto-Web.webp";
import Image from "next/image";

function Kontak() {
  return (
    <>
      <Head>
        <title>solotechnopark.go.id</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          href="https://solotechnopark.id/wp-content/uploads/2021/09/Solo-Tecno.png"
        />
      </Head>

      <main>
        <header className="bg-memphis bg-right-top bg-cover">
          <Navbar />
          <div className="container grid lg:grid-cols-2 mb-40 lg:h-[80vh]">
            <div className="flex flex-col justify-center items-start">
              <h3 className="head-4 mb-2">
                Beranda <span className="text-primary-100">/</span> Kontak
              </h3>
              <h1 className="head-1">Kontak</h1>
            </div>
            <div className="flex items-center justify-end">
              <Image className="w-full" src={HeroImage} alt="kontak image" />
            </div>
          </div>
        </header>
      </main>

      <Footer />
    </>
  );
}

export default Kontak;
